services:
  projectdefense.web:
    image: ${DOCKER_REGISTRY-}projectdefenseweb
    build:
      context: .
      dockerfile: ProjectDefense.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
